name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Install dependencies
      working-directory: ./server
      run: go mod download

    - name: Run tests
      working-directory: ./server
      run: go test ./...

    - name: Build
      working-directory: ./server
      run: go build -v ./...